<?php
/**
 * @var \LaPoste\Colissimo\Block\Prices\Import $block
 */
?>

<div id="lpc_prices_import">
    <form action="<?= $block->escapeUrl($block->getImportUrl()); ?>"
          method="POST"
          enctype="multipart/form-data">

        <input type="hidden"
               name="form_key"
               value="<?= $block->escapeHtmlAttr($block->getFormKey()); ?>">

        <div class="admin__field field field-import_file  required _required">
            <label class="label admin__field-label"
                   for="import_file">
                <span><?= $block->escapeHtml(__('Select File to Import')); ?></span>
            </label>

            <div class="admin__field-control control">
                <input id="import_file"
                       name="import_file"
                       value=""
                       title="<?= $block->escapeHtmlAttr(__('Select File to Import')); ?>"
                       class="input-file required-entry _required"
                       type="file">

                <div class="note admin__field-note"><?= $block->escapeHtml(__('Only CSV files are accepted')); ?></div>
            </div>
        </div>

        <div class="admin__field field">
            <div class="admin__field-control control">
                <a type="button"
                   href="<?= $block->escapeUrl($block->getBackUrl()); ?>"
                   class="action secondary">
                    <button type="button" class="secondary">
                        <?= $block->escapeHtml(__('Back')); ?>
                    </button>
                </a>
                <button type="submit"
                        class="action primary">
                    <?= $block->escapeHtml(__('Import CSV file')); ?>
                </button>
            </div>
        </div>
    </form>
</div>
