<?php
/**
 * @var $block \LaPoste\Colissimo\Block\Adminhtml\Order\View\Tab\CustomsTab
 */

$customsNeeded = $block->isDocumentsNeeded();
echo '<div class="fieldset-wrapper order-information">';

if ($customsNeeded) {
    $documentsTypes = $block->getDocumentTypes();
    $sentDocuments = $block->getSentDocuments();
    $trackingNumbers = $block->getParcelNumbers();
    $parcelShipmentRelations = $block->getParcelShipmentRelations();
    $ajaxUrl = $block->getAjaxUrlSendDocuments();
    ?>

    <div>
        <h2><?= $block->escapeHtml(__('Customs documents')); ?></h2>
    </div>
    <div class="lpc__admin__order_banner__content lpc__admin__order_banner__send_documents">
        <div style="margin-bottom: 1rem;">
            <?= $block->escapeHtml(__('In accordance with the customs regulation, it is necessary to provide documents related to the parcels for the customs.')); ?>
            <br />
            <?= $block->escapeHtml(__('It is possible to send these documents through the parcel tracking tool or using the module from here.')); ?>
        </div>
        <template id="lpc__admin__order_banner__send_documents__template">
            <tr>
                <td>
                    <select class="lpc__admin__order_banner__document__type">
                        <?php
                        foreach ($documentsTypes as $documentType => $description) {
                            echo '<option value="' . $block->escapeHtmlAttr($documentType) . '">' . $block->escapeHtml($description) . '</option>';
                        }
                        ?>
                    </select>
                </td>
                <td>
                    <input
                        type="file"
                        name="lpc__customs_document[__PARCELNUMBER__][__TYPE__][]"
                        class="lpc__admin__order_banner__document__file"
                        disabled="disabled" />
                </td>
            </tr>
        </template>
        <table class="admin__table-secondary">
            <thead>
                <?php foreach ($trackingNumbers as $outwardTrackingNumber) { ?>
                    <tr>
                        <th><?= $block->escapeHtml($outwardTrackingNumber); ?></th>
                        <td class="lpc__admin__order_banner__send_documents__container">
                            <img class="processing"
                                 style="display: none;"
                                 alt="Send customs documents spinner"
                                 src="<?= $block->escapeUrl($block->getViewFileUrl('images/process_spinner.gif')); ?>" />

                            <form data-lpc-formkey="<?= $block->escapeHtmlAttr($block->getFormKey()); ?>"
                                  data-lpc-ajaxurl="<?= $block->escapeUrl($ajaxUrl); ?>"
                                  data-lpc-shipmentid="<?= $block->escapeHtmlAttr(intval($parcelShipmentRelations[$outwardTrackingNumber])); ?>">
                                <table>
                                    <tbody class="lpc__admin__order_banner__send_documents__listing">
                                        <?php
                                        if (!empty($sentDocuments[$outwardTrackingNumber])) {
                                            foreach ($sentDocuments[$outwardTrackingNumber] as $oneDocument) {
                                                ?>
                                                <tr class="lpc__customs__sent__document">
                                                    <td>
                                                        <?= $block->escapeHtml($documentsTypes[$oneDocument['documentType']]); ?>
                                                    </td>
                                                    <td>
                                                        <?= $block->escapeHtml($oneDocument['documentName']); ?>
                                                    </td>
                                                </tr>
                                                <?php
                                            }
                                        }
                                        ?>
                                    </tbody>
                                </table>
                                <div class="lpc__buttons__container">
                                    <button type="button"
                                            class="lpc__admin__order_banner__send_documents__more"
                                            data-lpc-parcelnumber="<?= $block->escapeHtmlAttr($outwardTrackingNumber); ?>">
                                        <?= $block->escapeHtml(__('Add an other document')); ?>
                                    </button>
                                    <button type="submit" class="action-secondary lpc__admin__order_banner__send_documents__listing__send_button">
                                        <?= $block->escapeHtml(__('Submit the documents')); ?>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                <?php } ?>
            </thead>
        </table>
    </div>
    <?php
}
echo '</div>';
