<?php $lpcShippingNote = $block->lpcGetShippingNote();
if (!empty($lpcShippingNote)) { ?>
    <div class="admin__page-section-item lpc_shipping_notes_block">
        <div class="admin__page-section-item-title">
            <span class="title"><?= $block->escapeHtml(__('Shipping notes')); ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <?= $block->escapeHtml($lpcShippingNote); ?>
        </div>
    </div>
<?php } ?>
