<?php

/*******************************************************
 * Copyright (C) 2023 La Poste.
 *
 * This file is part of La Poste - Colissimo module.
 *
 * La Poste - Colissimo module can not be copied and/or distributed without the express
 * permission of La Poste.
 *******************************************************/

/* @var $block \LaPoste\Colissimo\Block\System\Config\Field\DownloadButton */ ?>

<?php echo $block->getButtonHtml(); ?>
