<?php echo $block->escapeHtml(__('We have detected that you have not yet signed the latest version of our GTC. Your consent is necessary in order to continue using Colissimo services. We therefore invite you to sign them on your Colissimo entreprise space, by clicking on the link below:')); ?>
<br>
<a target="_blank" href="https://www.colissimo.entreprise.laposte.fr"><?php echo $block->escapeHtml(__('Sign the GTC')); ?></a>
