<?php /** @var  $block \LaPoste\Colissimo\Block\Frontend\Order\ReturnalContent */ ?>

<div class="order-details-items lpcreturn">
    <div id="lpc_products_selection">
        <h3 id="lpcreturn_header">
            <?= $block->escapeHtml(__('Choose the products to return')); ?>
        </h3>

        <table class="data table table-order-items shipment">
            <thead>
                <tr>
                    <th class="col products">
                        <input type="checkbox" id="lpcreturn_header_selectall" title="<?= $block->escapeHtmlAttr(__('Select all products')); ?>">
                        <?= $block->escapeHtml(__('Product')); ?>
                    </th>
                    <th class="col quantity"><?= $block->escapeHtml(__('Quantity')); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php $products = $block->getShippedProducts(); ?>
                <?php foreach ($products as $productId => $oneProduct): ?>
                    <tr>
                        <td class="col product-name" data-th="<?= $block->escapeHtmlAttr(__('Product')); ?>">
                            <label>
                                <input type="checkbox" class="lpcreturn_selection" value="<?= $block->escapeHtmlAttr(intval($productId)); ?>">
                                <?= $block->escapeHtml($oneProduct['name']); ?>
                            </label>
                        </td>
                        <td class="col product-quantity" data-th="<?= $block->escapeHtmlAttr(__('Quantity')); ?>">
                            <select class="lpcreturn_quantity" data-product-id="<?= $block->escapeHtmlAttr(intval($productId)); ?>">
                                <?php for ($i = 1; $i <= $oneProduct['quantity']; $i ++): ?>
                                    <option value="<?= $block->escapeHtmlAttr($i); ?>" <?= $i === $oneProduct['quantity'] ? 'selected="selected"' : ''; ?>><?= $block->escapeHtml($i); ?></option>
                                <?php endfor; ?>
                            </select>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <button type="button"
                title="<?= $block->escapeHtmlAttr(__('Generate inward shipping label')); ?>"
                class="action primary"
                id="lpcreturn_download">
            <span><?= $block->escapeHtml($block->getReturnButtonLabel()); ?></span>
        </button>
        <?php
        $balReturnLink = $block->mailBoxPickUpLink();
        if (!empty($balReturnLink)) {
            ?>
            <button title="<?= $block->escapeHtmlAttr(__('MailBox picking return')); ?>"
                    class="action"
                    id="lpcbalreturn">
                <span><?= $block->escapeHtml(__('MailBox picking return')); ?></span>
            </button>
        <?php } ?>
    </div>
    <div id="lpc_return_label_confirmation">
        <?php
        printf(
            __($block->isSecuredReturn() ? 'Your secured code for the return label %s has been generated.' : 'Your label %s has been generated.'),
            '<span id="lpc_return_label_confirmation_tracking_number"></span>'
        );
        ?>
    </div>
    <div id="lpc_return_instructions_container">
        <p id="instructions_title"><?= $block->escapeHtml(__('How to return your parcel?')); ?></p>
        <ol>
            <li><?= $block->escapeHtml(__('Pack your products.')); ?></li>

            <?php if ($block->isSecuredReturn()) { ?>
                <li>
                    <?= $block->escapeHtml(__('Go to the post office of your choice:')); ?>
                    <a target="_blank" href="https://localiser.laposte.fr/?jesuis=particulier&contact=vente&qp=<?= $block->escapeHtmlAttr($block->getShippingPostcode()); ?>">https://localiser.laposte.fr</a>
                </li>
                <li>
                    <?= $block->escapeHtml(__('At the drop-off point, present your barcode to your contact or to the machine (or your 9-character code) to have your label printed and make your deposit.')); ?>
                </li>
            <?php } else { ?>
                <li><?= $block->escapeHtml(__('Print your label and stick it on your parcel.')); ?></li>
                <li>
                    <?= $block->escapeHtml(__('Drop off your parcel at the post office of your choice:')); ?>
                    <a target="_blank" href="https://localiser.laposte.fr/?jesuis=particulier&contact=vente&qp=<?= $block->escapeHtmlAttr($block->getShippingPostcode()); ?>">https://localiser.laposte.fr</a>
                </li>
            <?php } ?>

            <li>
                <?php
                printf(
                    __('Track your parcel shipment on %s'),
                    '<a target="_blank" href="https://laposte.fr/outils/suivre-vos-envois">https://laposte.fr/suivi</a>'
                )
                ?>
            </li>
        </ol>
    </div>
    <input type="hidden" value="<?= $block->escapeUrl($block->getReturnLabelDownloadUrl()); ?>" id="returnLabelDownloadUrl" />
    <input type="hidden" value="<?= $block->escapeUrl($balReturnLink); ?>" id="balReturnUrl" />
    <input type="hidden" value="<?= $block->escapeHtmlAttr($block->getOrder()->getId()); ?>" id="lpcOrderId" />
</div>
