<?php
/**
 * @var $block \LaPoste\Colissimo\Block\Adminhtml\Order\MultiShipping
 * @var $csp   \Magento\Csp\Api\InlineUtilInterface
 */


if ($block->isOmShipment()) {
    $data = $block->getMultiShippingData();
    $readonly = empty($data['amount']) ? '' : 'readonly';
    $checked = empty($data['amount']) ? '' : 'checked';
    $maxValue = max(2, min($block->getOrderQty(), 4));
    ?>
    <section class="admin__page-section">
        <div id="colissimo_multi_parcels">
            <div class="admin__page-section-title">
                <span class="title"><?= $block->escapeHtml(__('Colissimo Multi Parcels')); ?></span>
            </div>
            <div class="admin__field">
                <label for="lpc_use_multi_parcels"><?= $block->escapeHtml(__('Use the multi-parcels shipping')); ?></label>
                <?php if (empty($checked)) { ?>
                    <input type="checkbox"
                           name="lpcMultiShipping[lpc_use_multi_parcels]"
                           id="lpc_use_multi_parcels">
                <?php } else { ?>
                    <input type="checkbox"
                           name="lpcMultiShipping[lpc_use_multi_parcels]"
                           id="lpc_use_multi_parcels"
                           onclick="return false;"
                           checked="checked">
                <?php } ?>
                <br />
                <label for="lpc_multi_parcels_amount">
                    <span><?= $block->escapeHtml(__('Number of parcels')); ?></span>
                </label>
                <input type="number"
                       min="2"
                       max="<?= $block->escapeHtmlAttr($maxValue); ?>"
                       name="lpcMultiShipping[lpc_multi_parcels_amount]"
                       id="lpc_multi_parcels_amount"
                       value="<?= $block->escapeHtmlAttr(intval($data['amount'])); ?>" <?= $block->escapeHtmlAttr($readonly); ?>><br />
            </div>
            <?php if (!empty($block->getShipment()->getId())) { ?>
                <div class="lpc_add_data_button admin__field">
                    <input type="hidden" name="lpcMultiShipping[shipment_id]" value="<?= $block->escapeHtmlAttr($block->getShipment()->getId()); ?>">
                    <input type="hidden" name="lpcMultiShipping[order_id]" value="<?= $block->escapeHtmlAttr($block->getOrderFromShipment()->getId()); ?>">
                    <?= $block->getChildHtml('submit_multiShipping') ?>
                </div>
            <?php } ?>
        </div>
        <script>
            require(['prototype'], function () {
                submitMultiShipping = function () {
                    submitAndReloadArea($('colissimo_multi_parcels').parentNode, '<?= $block->escapeJs($block->getSubmitUrl()); ?>');
                };
                if ($('submit_multiShipping_button')) {
                    $('submit_multiShipping_button').observe('click', submitMultiShipping);
                }
            });
        </script>
    </section>
    <?php
}
