<?php
/**
 * @var $block \LaPoste\Colissimo\Block\Adminhtml\Order\PickupSelection
 * @var $csp   \Magento\Csp\Api\InlineUtilInterface
 */

$lpcAjaxSetInformationRelayUrl = $block->getAjaxSetInformationRelayUrl();
$lpcPrView = $block->lpcPickupType();
$lpcAddressTextColor = $block->lpcGetAddressTextColor();
$lpcListTextColor = $block->lpcGetListTextColor();
$lpcWidgetFont = $block->lpcGetFontWidgetPr();
$lpcCustomizeWidget = $block->lpcGetCustomizeWidget();
$lpcUrlLoadRelaysList = $block->lpcAjaxUrlLoadRelaysList();
$lpcAutoSelectRelay = $block->lpcIsAutoRelay();

//TODO The Colissimo widget generates CSP errors, and the Google Maps API v3 can't be used because Magento modifies Array.from()
$lpcPrView = 'leaflet';
?>
    <input type="hidden" id="lpc_relay_mode" value="<?php echo $lpcPrView; ?>">
    <input type="hidden" id="lpc_webservice_relay_url" value="<?php echo $lpcUrlLoadRelaysList; ?>">
    <input type="hidden" id="lpc_auto_select_relay" value="<?php echo empty($lpcAutoSelectRelay) ? 'false' : 'true'; ?>">
    <input type="hidden" id="lpc_pickup_carrier_code" value="<?php echo $block->getPickupCarrierCode(); ?>">
    <template id="lpc_choose_relay_button_template">
        <section id="order-lpc-pickup" class="admin__page-section lpc-pickup" style="display: none; margin-top: -2rem;">
            <div id="colissimo_pickup_button_section" style="margin-left: calc(50% + 30px);">
                <div class="admin__page-section-title" style="display:none;"></div>
                <div class="lpc_add_data_button admin__field">
                    <div id="lpc_chosen_relay"></div>
                    <?php echo $block->getChildHtml('lpc_choose_relay_button') ?>
                </div>
            </div>
        </section>
    </template>
<?php

echo '<input type="hidden" id="lpc_map_marker" value="' . $block->getViewFileUrl('LaPoste_Colissimo::images/map_marker.png') . '">';
echo '<input type="hidden" id="lpc_ajax_set_information_relay_url" value="' . $lpcAjaxSetInformationRelayUrl . '">';

if (in_array($lpcPrView, ['gmaps', 'leaflet'])) {
    $prDefaultMobileDisplay = $block->lpcGetDefaultMobileDisplay();
    $maxRelayPoint = $block->lpcGetMaxRelayPoint();

    if ('gmaps' === $lpcPrView) {
        $lpcGoogleMapsUrl = $block->getGoogleMapsUrl();

        if (empty($lpcGoogleMapsUrl)) {
            $block->colissimoLogger->error('Error: no Google Maps API Key defined');
        } else {
            echo '<script src="' . $lpcGoogleMapsUrl . '"></script>';
        }
        ?>
    <?php } elseif ('leaflet' === $lpcPrView) { ?>
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('LaPoste_Colissimo::css/leaflet.css'); ?>">
    <?php }
    $classMap = '';
    if ($prDefaultMobileDisplay == 'list') {
        $classList = 'lpc_layer_list_active';
        $classMapList = 'lpc_layer_list_inactive';
        $classMap = 'class="lpc_mobile_display_none"';
    } else {
        $classList = 'lpc_layer_list_inactive';
        $classMapList = 'lpc_layer_list_active';
    }
    ?>
    <div id="lpc_layer_relays" style="display:none;">
        <div class="content">
            <span id="lpc_layer_relay_switch_mobile">
                <img alt="Switch to list mode icon" class="lpc_layer_relay_switch_mobile_icon lpc_layer_list <?php echo $classList; ?>"
                     src="<?php echo $this->getViewFileUrl('LaPoste_Colissimo::images/list.png'); ?>">
                <img alt="Switch to map mode icon" class="lpc_layer_relay_switch_mobile_icon lpc_layer_map <?php echo $classMapList; ?>"
                     src="<?php echo $this->getViewFileUrl('LaPoste_Colissimo::images/map.png'); ?>">
            </span>
            <div>
                <input type="text" id="lpc_modal_relays_search_address" class="lpc_modal_relays_search_input" placeholder="<?php echo __('Address'); ?>">
                <input type="text" id="lpc_modal_relays_search_zipcode" class="lpc_modal_relays_search_input" placeholder="<?php echo __('Zipcode'); ?>">
                <input type="text" id="lpc_modal_relays_search_city" class="lpc_modal_relays_search_input" placeholder="<?php echo __('City'); ?>">
                <button id="lpc_layer_button_search" type="button"><?php echo __('Search'); ?></button>
                <img id="lpc_layer_relays_loader" src="<?php echo $this->getViewFileUrl('LaPoste_Colissimo::images/loading.gif'); ?>" alt="Loading..." style="display: none">
                <?php if ($maxRelayPoint < 20) { ?>
                    <div id="lpc_modal_relays_display_more"><a href="#"><?php echo __('Display more pickup points'); ?></a></div>
                <?php } ?>
            </div>
            <div id="lpc_left" <?php echo $classMap; ?>>
                <div id="lpc_map"></div>
            </div>
            <div id="lpc_right">
                <div id="lpc_layer_error_message" style="display: none"></div>
                <div id="lpc_layer_list_relays"></div>
            </div>
        </div>
    </div>
    <?php
} else {
    // Use the Colissimo widget
    $lpcToken = $block->lpcGetAuthenticationToken();
    if ($lpcToken !== false) {
        ?>
        <input type="hidden" id="lpc_widget_list_country" value="<?php echo $block->getWidgetListCountry(); ?>">
        <input type="hidden" id="lpc_mapbox_script" value="<?php echo $block->getViewFileUrl('LaPoste_Colissimo::js/widget/mapbox.min.js'); ?>">
        <link rel="stylesheet" type="text/css" href="https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css">
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('LaPoste_Colissimo::css/widget.css'); ?>">

        <div id="lpc_layer_widget" style="display: none">
            <div id="lpc_widget_container" class="widget_colissimo"></div>
        </div>
        <input type="hidden" id="lpc_token_widget" value="<?php echo $lpcToken ?>">
        <input type="hidden" id="lpc_average_preparation_delay" value="<?php echo $block->lpcGetAveragePreparationDelay() ?>">
        <input type="hidden" id="lpc_relay_types" value="<?php echo $block->lpcGetRelayTypes(); ?>">
        <?php if ($lpcCustomizeWidget) { ?>
            <input type="hidden" id="lpc_color_1" value="<?php echo $lpcAddressTextColor ?>">
            <input type="hidden" id="lpc_color_2" value="<?php echo $lpcListTextColor ?>">
            <input type="hidden" id="lpc_font" value="<?php echo $block->escapeHtmlAttr($lpcWidgetFont) ?>">
        <?php } ?>
    <?php } else { ?>
        <div id="lpc_error_pr" style="display: none">
            <p id="lpc_error_message_pr"><?php echo __('The window to choose your pickup point is currently unavailable. Please refresh the page and try again. If the problem persists, please contact the website administrator.') ?></p>
        </div>
    <?php }
}
