<?php
$listRelays = $block->getListRelays();
$openingDays = [
    'Monday'    => 'horairesOuvertureLundi',
    'Tuesday'   => 'horairesOuvertureMardi',
    'Wednesday' => 'horairesOuvertureMercredi',
    'Thursday'  => 'horairesOuvertureJeudi',
    'Friday'    => 'horairesOuvertureVendredi',
    'Saturday'  => 'horairesOuvertureSamedi',
    'Sunday'    => 'horairesOuvertureDimanche',
];

if ($block->getOverWarning()) {
    echo '<div class="lpc_layer_relay_warning_relay_type">' . $block->escapeHtml(__('Only post offices are available for this order')) . '</div>';
}
foreach ($listRelays as $i => $oneRelay) { ?>
    <div class="lpc_layer_relay" id="lpc_layer_relay_<?= $block->escapeHtmlAttr($i); ?>" data-relayindex="<?= $block->escapeHtmlAttr($i); ?>">
        <div class="lpc_layer_relay_distance">
            <img class="lpc_relay_marker" src="<?= $block->escapeUrl($block->getViewFileUrl('LaPoste_Colissimo::images/map_marker.png')); ?>">
            <?= $block->escapeHtml(__('At') . " " . $oneRelay->distanceEnMetre) ?> m
        </div>
        <div class="lpc_layer_relay_name"><?= $block->escapeHtml($oneRelay->nom) ?></div>
        <div class="lpc_layer_relay_address">
            <span class="lpc_layer_relay_country_code"><?= $block->escapeHtml($oneRelay->codePays); ?></span>
            <span class="lpc_layer_relay_type"><?= $block->escapeHtml($oneRelay->typeDePoint); ?></span>
            <span class="lpc_layer_relay_id"><?= $block->escapeHtml($oneRelay->identifiant); ?></span>
            <span class="lpc_layer_relay_address_street"><?= $block->escapeHtml($oneRelay->adresse1); ?></span>
            <span class="lpc_layer_relay_address_zipcode"><?= $block->escapeHtml($oneRelay->codePostal); ?></span><?= " "; ?>
            <span class="lpc_layer_relay_address_city"><?= $block->escapeHtml($oneRelay->localite) ?></span>
            <span class="lpc_layer_relay_latitude"><?= $block->escapeHtml($oneRelay->coordGeolocalisationLatitude); ?></span>
            <span class="lpc_layer_relay_longitude"><?= $block->escapeHtml($oneRelay->coordGeolocalisationLongitude); ?></span>
            <span class="lpc_layer_relay_distance_nb"><?= $block->escapeHtml($oneRelay->distanceEnMetre); ?></span>
            <span class="lpc_layer_relay_hour">
                <table>
                    <?php
                    foreach ($openingDays as $day => $oneDay) {
                        if (empty($oneRelay->$oneDay) || ' ' === $oneRelay->$oneDay || '00:00-00:00 00:00-00:00' === $oneRelay->$oneDay) {
                            continue;
                        }
                        echo $block->escapeHtml(ucfirst(__($day)) . ' ' . str_replace(' 00:00-00:00', '', $oneRelay->$oneDay)) . '<br />';
                    }
                    ?>
                </table>
            </span>
            <div class="lpc_layer_relay_schedule">
                <table cellspacing="0" cellpadding="0">
                    <?php
                    foreach ($openingDays as $day => $oneDay) {
                        if (empty($oneRelay->$oneDay) || ' ' === $oneRelay->$oneDay || '00:00-00:00 00:00-00:00' === $oneRelay->$oneDay) {
                            continue;
                        }
                        echo '<tr><td>' . $block->escapeHtml(ucfirst(__($day))) . '</td><td class="opening_hours">' . $block->escapeHtml($block->formatRelaysOpeningHours($oneRelay->$oneDay)) . '</td></tr>';
                    }
                    ?>
                </table>
            </div>

        </div>
        <div class="lpc_relay_choose_btn">
            <span class="lpc_show_relay_details"><?= $block->escapeHtml(__('Display on map')) ?></span>
            <button class="lpc_relay_choose" type="button" data-relayindex="<?= $block->escapeHtmlAttr($i); ?>"><?= $block->escapeHtml(__('Choose')) ?></button>
        </div>

    </div>
    <?php if (($i + 1) < count($listRelays)) { ?>
        <hr style="width: 100%">
    <?php } ?>

<?php } ?>
