<div class="lpc_tracking_logo">
    <img src="<?= $block->escapeUrl($this->getViewFileUrl('LaPoste_Colissimo::images/Colissimo_logo.png')); ?>"
         alt="Logo colissimo" />
</div>

<h2 class="lpc_tracking_title"><?= $block->escapeHtml(__('Tracking information for order')); ?>
    <b>#<?= $block->escapeHtml($this->getOrder()->getIncrementId()); ?></b></h2>
<p class="lpc_tracking_method">
    <?= $block->escapeHtml(__('Shipping method:')); ?> <b><?= $block->escapeHtml($this->getOrder()->getShippingDescription()); ?></b>
</p>

<?php foreach ($this->getTracks() as $track) {
    $status = $this->getStatusForTrack($track);
    $trackingNumber = $status->parcel->parcelNumber; ?>

    <hr class="lpc_tracking_separator">

    <div class="lpc_tracking_summary">
        <table>
            <thead>
                <tr>
                    <th><?= $block->escapeHtml(__('Tracking number')); ?></th>
                    <th><?= $block->escapeHtml(__('Status')); ?></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="lpc_tracking_tracknumber"><?= $block->escapeHtml($trackingNumber); ?></td>
                    <td><?= $block->escapeHtml($this->getMainStatus($status)); ?></td>
                    <td>
                        <a target="_blank"
                           href="https://www.laposte.fr/particulier/modification-livraison?code=<?= $block->escapeHtmlAttr($trackingNumber); ?>"><?= $block->escapeHtml(__('Change your shipping information and options')); ?></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="lpc_tracking_message">
        <?= $block->escapeHtml(!empty($status->message->message) ? $status->message->message : ''); ?>
    </div>

    <h3><?= $block->escapeHtml(__('Status history')); ?></h3>
    <div class="lpc_tracking_events">
        <table>
            <thead>
                <tr>
                    <th><?= $block->escapeHtml(__('Status Date')); ?></th>
                    <th><?= $block->escapeHtml(__('Status')); ?></th>
                    <th><?= $block->escapeHtml(__('Localisation')); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($status->parcel->event as $event) {
                    ?>
                    <tr>
                        <td><?= $block->escapeHtml($this->formatDate($event->date, IntlDateFormatter::SHORT)); ?></td>
                        <td><?= $block->escapeHtml($event->labelLong); ?></td>
                        <td><?= $block->escapeHtml($event->siteCity ?? '-'); ?></td>
                    </tr>
                    <?php
                } // foreach $event
                ?>
            </tbody>
        </table>
    </div>

    <h3><?= $block->escapeHtml(__('Timeline')); ?></h3>
    <div class="lpc_tracking_events lpc_tracking_timeline">
        <table>
            <thead>
                <tr>
                    <th><?= $block->escapeHtml(__('Step number')); ?></th>
                    <th><?= $block->escapeHtml(__('Status')); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                $stepNumber = 0;
                foreach ($status->parcel->step as $step) {
                    if (empty($step->labelShort) && empty($step->labelLong)) {
                        continue;
                    }
                    $classActive = '';
                    if ('STEP_STATUS_ACTIVE' === $step->status) {
                        $classActive = 'lpc_active_step';
                    }
                    $stepNumber ++;
                    ?>
                    <tr class="<?= $block->escapeHtmlAttr($classActive); ?>">
                        <td><?= $block->escapeHtml($stepNumber); ?></td>
                        <td><?= $block->escapeHtml(empty($step->labelLong) ? $step->labelShort : $step->labelLong); ?></td>
                    </tr>
                    <?php
                }
                ?>
            </tbody>
        </table>
    </div>
    <?php
} // foreach $track
